/**
 * @author Anonyfox <max@anonyfox.com>
 * @license MIT
 * @see {@link https://github.com/Anonyfox/ravenjs}
 * @see {@link https://ravenjs.dev}
 * @see {@link https://anonyfox.com}
 */

/**
 * Base HTML template with Bootstrap 5, SEO, and responsive design
 *
 * Foundation template providing consistent structure for all documentation pages.
 * Surgical design optimized for documentation presentation and developer UX.
 */

import { html } from "@raven-js/beak";

/**
 * Generate base HTML template with Bootstrap 5 layout
 * @param {Object} options - Template configuration
 * @param {string} options.title - Page title
 * @param {string} options.description - Meta description
 * @param {string} options.packageName - Package name for branding
 * @param {string} options.content - Main page content HTML
 * @param {Object} [options.seo] - SEO configuration
 * @param {string} [options.seo.url] - Canonical URL
 * @param {string} [options.seo.image] - Open Graph image
 * @param {Object} [options.navigation] - Navigation data
 * @param {string} [options.navigation.current] - Current active page
 * @param {boolean} [options.navigation.showSearch] - Show search form
 * @param {string} [options.navigation.sidebar] - Sidebar content
 * @returns {string} Complete HTML document
 */
export function baseTemplate({
	title,
	description,
	packageName,
	content,
	seo = {},
	navigation = {},
}) {
	const fullTitle = packageName
		? `${title} - ${packageName} Documentation`
		: title;
	const canonicalUrl = seo.url || "";
	const ogImage = seo.image || "";

	return html`<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<!-- Core Meta Tags -->
	<title>${fullTitle}</title>
	<meta name="description" content="${description}">
	<meta name="generator" content="Glean Documentation Generator">
	<meta name="theme-color" content="#6366f1">

	<!-- Open Graph Meta Tags -->
	<meta property="og:type" content="website">
	<meta property="og:title" content="${title}">
	<meta property="og:description" content="${description}">
	${canonicalUrl ? html`<meta property="og:url" content="${canonicalUrl}">` : ""}
	${ogImage ? html`<meta property="og:image" content="${ogImage}">` : ""}
	<meta property="og:site_name" content="${packageName} Documentation">

	<!-- Twitter Card Meta Tags -->
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:title" content="${title}">
	<meta name="twitter:description" content="${description}">
	${ogImage ? html`<meta name="twitter:image" content="${ogImage}">` : ""}

	<!-- SEO Meta Tags -->
	${canonicalUrl ? html`<link rel="canonical" href="${canonicalUrl}">` : ""}
	<meta name="robots" content="index, follow">
	<meta name="author" content="Generated by Glean">

	<!-- Favicon -->
	<link rel="icon" type="image/x-icon" href="/favicon.ico">

	<!-- Bootstrap 5 CSS -->
	<link href="/bootstrap.min.css" rel="stylesheet">

	<!-- Custom Documentation Styles -->
	<style>
		:root {
			--glean-primary: #6366f1;
			--glean-secondary: #64748b;
			--glean-accent: #f59e0b;
			--glean-surface: #f8fafc;
			--glean-border: #e2e8f0;
		}

		body {
			font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
			line-height: 1.6;
			color: #334155;
		}

		.navbar-brand {
			font-weight: 600;
			color: var(--glean-primary) !important;
		}

		.sidebar {
			background-color: var(--glean-surface);
			border-right: 1px solid var(--glean-border);
			min-height: calc(100vh - 56px);
		}

		.content-area {
			min-height: calc(100vh - 56px);
			padding: 2rem;
		}

		.nav-link {
			color: var(--glean-secondary);
			transition: color 0.2s ease;
		}

		.nav-link:hover, .nav-link.active {
			color: var(--glean-primary);
		}

		.code-block {
			background-color: #f1f5f9;
			border: 1px solid var(--glean-border);
			border-radius: 0.5rem;
			padding: 1rem;
			font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
			font-size: 0.875rem;
		}

		.breadcrumb {
			background-color: transparent;
			padding: 0;
			margin-bottom: 1.5rem;
		}

		.breadcrumb-item + .breadcrumb-item::before {
			content: "›";
			color: var(--glean-secondary);
		}

		.search-highlight {
			background-color: rgba(245, 158, 11, 0.2);
			padding: 0.125rem 0.25rem;
			border-radius: 0.25rem;
		}

		/* Module Directory Card Improvements */
		.card {
			transition: transform 0.2s ease, box-shadow 0.2s ease;
		}

		.card:hover {
			transform: translateY(-2px);
			box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1) !important;
		}

		/* Improve text overflow handling */
		.text-truncate {
			word-wrap: break-word;
			overflow-wrap: break-word;
		}

		/* Better markdown content handling */
		.card-body .text-muted div {
			line-height: 1.4;
		}

		/* Improve entity badges */
		.badge {
			font-size: 0.75rem;
			font-weight: 500;
		}

		/* Better responsive grid */
		@media (max-width: 1400px) {
			.col-xl-3 {
				margin-bottom: 1rem;
			}
		}

		@media (max-width: 992px) {
			.col-lg-4 {
				margin-bottom: 1rem;
			}
		}

		@media (max-width: 768px) {
			.content-area {
				padding: 1rem;
			}

			.sidebar {
				min-height: auto;
			}

			.card-body {
				padding: 1rem;
			}

			.col-md-6 {
				margin-bottom: 1rem;
			}
		}

		/* Ensure grid items have proper spacing */
		.row.g-4 > [class*="col-"] {
			margin-bottom: 1.5rem;
		}

		/* Improve card sizing */
		.card {
			height: 100%;
			display: flex;
			flex-direction: column;
		}

		.card-body {
			flex: 1;
			display: flex;
			flex-direction: column;
		}
	</style>
</head>
<body>
	<!-- Main Navigation -->
	<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
		<div class="container-fluid">
			<a class="navbar-brand" href="/">
				<strong>${packageName}</strong> Documentation
			</a>

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link ${navigation.current === "overview" ? "active" : ""}" href="/">Overview</a>
					</li>
					<li class="nav-item">
						<a class="nav-link ${navigation.current === "modules" ? "active" : ""}" href="/modules/">Modules</a>
					</li>
					<li class="nav-item">
						<a class="nav-link ${navigation.current === "api" ? "active" : ""}" href="/api/">API Reference</a>
					</li>
				</ul>

				<!-- Search Form (if enabled) -->
				${
					navigation.showSearch
						? html`
				<form class="d-flex" role="search">
					<input class="form-control me-2" type="search" placeholder="Search documentation..." aria-label="Search">
					<button class="btn btn-outline-primary" type="submit">Search</button>
				</form>
				`
						: ""
				}
			</div>
		</div>
	</nav>

	<!-- Main Content Area -->
	<div class="container-fluid">
		<div class="row">
			<!-- Sidebar Navigation (if provided) -->
			${
				navigation.sidebar
					? html`
			<div class="col-md-3 col-lg-2">
				<div class="sidebar p-3">
					${navigation.sidebar}
				</div>
			</div>
			`
					: ""
			}

			<!-- Main Content -->
			<div class="${navigation.sidebar ? "col-md-9 col-lg-10" : "col-12"}">
				<main class="content-area">
					${content}
				</main>
			</div>
		</div>
	</div>

	<!-- Footer -->
	<footer class="bg-light border-top py-4 mt-5">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<p class="text-muted mb-0">
						Generated by <a href="https://ravenjs.dev" class="text-decoration-none">Glean</a>
						- Part of the RavenJS toolkit
					</p>
				</div>
				<div class="col-md-6 text-md-end">
					<p class="text-muted mb-0">
						<small>Last updated: ${new Date().toISOString().split("T")[0]}</small>
					</p>
				</div>
			</div>
		</div>
	</footer>

	<!-- Bootstrap 5 JavaScript -->
	<script src="/bootstrap.esm.js" type="module"></script>

	<!-- Enhanced Documentation Features -->
	<script>
		// Smooth scrolling for anchor links
		document.querySelectorAll('a[href^="#"]').forEach(anchor => {
			anchor.addEventListener('click', function (e) {
				e.preventDefault();
				const target = document.querySelector(this.getAttribute('href'));
				if (target) {
					target.scrollIntoView({ behavior: 'smooth' });
				}
			});
		});

		// Copy code block functionality
		document.querySelectorAll('.code-block').forEach(block => {
			const copyBtn = document.createElement('button');
			copyBtn.className = 'btn btn-sm btn-outline-secondary position-absolute top-0 end-0 m-2';
			copyBtn.textContent = 'Copy';
			copyBtn.onclick = () => {
				navigator.clipboard.writeText(block.textContent);
				copyBtn.textContent = 'Copied!';
				setTimeout(() => copyBtn.textContent = 'Copy', 2000);
			};
			block.style.position = 'relative';
			block.appendChild(copyBtn);
		});

		// Search highlighting (basic implementation)
		const searchParams = new URLSearchParams(window.location.search);
		const searchTerm = searchParams.get('search');
		if (searchTerm) {
			const walker = document.createTreeWalker(
				document.querySelector('main'),
				NodeFilter.SHOW_TEXT
			);
			let node;
			while (node = walker.nextNode()) {
				if (node.textContent.toLowerCase().includes(searchTerm.toLowerCase())) {
					const highlightedText = node.textContent.replace(
						new RegExp(searchTerm, 'gi'),
						'<span class="search-highlight">$&</span>'
					);
					const wrapper = document.createElement('span');
					wrapper.innerHTML = highlightedText;
					node.parentNode.replaceChild(wrapper, node);
				}
			}
		}
	</script>
</body>
</html>`;
}
